### ISSUE TITLE
Some webcam streams work others don't

### ISSUE THREAD

**Issue by marksev1** [earendil06/Windy-Webcams#2]
I would like to report that some webcam streams work, while others not. Is it a problem with an API limitation or some other problem?
I can get 3 webcam's to work, while for the 3 others the state is "unknown". On  the Windy website they are active.

**Comment by earendil06** [comment]
Hello,
Thanks for sharing your experience. Could you please provide more infos like the not working IDs ?

**Comment by radzio** [comment]
One of the examples: https://www.windy.com/-Webcams-Planty-ZAMO%C5%9A%C4%86-widok-na-Rynek-Wielki/webcams/1601392527?50.716,23.253,10

**Comment by marksev1** [comment]
I get about 33% luck that the cam's are working. Still good, but would be better, if it was 100% :).

For example:

https://www.windy.com/-Webcams-Piran-Livecam-Portoro%C5%BE-beach/webcams/1600352001?45.513,13.595,13,m:eU2agxV

When I get home I will update with more links.

**Comment by earendil06** [comment]
I directly tested the http endpoint out of the integration with your provided IDs. I got a 404.
I tried to find on the web such issues related to the API itself and I found this: https://community.windy.com/topic/23527/missing-webcams-in-the-api

I'm afraid it’s a limitation

**Comment by marksev1** [comment]
Thanks for clarification, closing issue!
